In [6]:
### Code for SCARA both Position and Jacobian
import numpy as np
from numpy import pi, sin, cos, sqrt, absolute, arccos, arctan, sign
import matplotlib.pyplot as plt
a1,a2 = 5,5
q = input("Enter the joint angles in degrees q1,q2 :")
d = float(input("Enter extension of end-effector :"))
ang1,ang2 = float(q.split(",")[0]) , float(q.split(",")[1])
q1,q2 = ang1*3.14/180, ang2*3.14/180
end_pos = [0,0,0,1]
theta,alpha,dis,a = 0,0,0,0
dh = [[cos(theta), -sin(theta)*cos(alpha), sin(theta)*sin(alpha), cos(theta)*a],
[sin(theta), cos(theta)*cos(alpha), -cos(theta)*sin(alpha), sin(theta)*a],
[0, sin(alpha), cos(alpha),d],
[0,0,0,1]]
t = [[cos(q1+q2),sin(q1+q2),0,a1*cos(q1)+a2*cos(q1+q2)],
[sin(q1+q2),-cos(q1+q2),0,a1*sin(q1)+a2*sin(q1+q2)],
[0,0,-1,-d],
[0,0,0,1]]
res = np.dot(t,end_pos)
print("Position :" +str(res) )
z0,z1,z2 =np.array([0,0,1]),np.array([0,0,1]),np.array([0,0,1])
o,o1,o2,o3 = np.array([0,0,0]),np.array([a1*cos(q1),a1*sin(q1),0]),np.array([a1*cos(q1)+a2*cos(q1+q2),a1*sin(q1)+ a2*sin(q1+q2),0]),np.array([a1*cos(q1)+a2*cos(q1+q2),a1*sin(q1)+ a2*sin(q1+q2),d])
jacob = [np.transpose(np.cross(z0,o3-o)).tolist(),np.transpose(np.cross(z1,o3-o1)).tolist(),np.transpose(z2).tolist()],[np.transpose(z0).tolist(),np.transpose(z1).tolist(),np.transpose(z2).tolist()]
print("Jacobian :"+ str(jacob))

Position :[10.  0. -3.  1.]
Jacobian :([[0.0, 10.0, 0.0], [0.0, 5.0, 0.0], [0, 0, 1]], [[0, 0, 1], [0, 0, 1], [0, 0, 1]])


Code to get position of Stanford Manipulator

In [7]:
import numpy as np
from numpy import pi, sin, cos, sqrt, absolute, arccos, arctan, sign
import matplotlib.pyplot as plt
a1,a2 = 5,5
q = input("Enter the joint angles in degrees q1,q2 :")
d = float(input("Enter extension of end-effector :"))
ang1,ang2 = float(q.split(",")[0]) , float(q.split(",")[1])
q1,q2 = ang1*3.14/180, ang2*3.14/180
end_pos = [0,0,0,1]
#theta,alpha,dis,a = 0,0,0,0
def get_dh(theta,alpha,d,a):
    dh = [[cos(theta), -sin(theta)*cos(alpha), sin(theta)*sin(alpha), cos(theta)*a],
    [sin(theta), cos(theta)*cos(alpha), -cos(theta)*sin(alpha), sin(theta)*a],
    [0, sin(alpha), cos(alpha),d],
    [0,0,0,1]]
    return dh
qs = [q1,q2,0]
ds = [0,0,d]
aas = [0,0,0]
alphas = [-3.14/2,3.14/2,0]
t = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
z0,z1,z2 =np.array([0,0,1]),np.array([0,0,1]),np.array([0,0,1])
o = [[],[],[]]
#t = get_dh(qs[0],alphas[0],ds[0],aas[0])
#print(t)
for i in range(0,3):
    #t2 = get_dh(qs[i],alphas[i],ds[i],aas[i])
    t = np.dot(t,get_dh(qs[i],alphas[i],ds[i],aas[i]))
    o[i] = np.dot(t,[0,0,0,1])[0:3]
    #print(o[i])
    #print(t)
res = np.dot(t,end_pos)
print(res)
# print([-cos(q1)*sin(q2)*d, sin(q1)*sin(q2)*d, -cos(q2)*d,1])

[0. 0. 0.]
[0. 0. 0.]
[0.00000000e+00 2.82887083e-20 3.00000000e+00]
[0.00000000e+00 2.82887083e-20 3.00000000e+00 1.00000000e+00]


Code to get the jacobian of # link planar manipulator

In [11]:
import numpy as np
from numpy import pi, sin, cos, sqrt, absolute, arccos, arctan, sign

a1,a2,a3 = 5,5,5
q = input("Enter the joint angles in degrees q1,q2,q3 :")

ang1,ang2,ang3 = float(q.split(",")[0]) , float(q.split(",")[1]),float(q.split(",")[2])
q1,q2,q3 = ang1*3.14/180, ang2*3.14/180,ang3*3.14/180
end_pos = [0,0,0,1]
#theta,alpha,dis,a = 0,0,0,0
def get_dh(theta,alpha,d,a):
    dh = [[cos(theta), -sin(theta)*cos(alpha), sin(theta)*sin(alpha), cos(theta)*a],
    [sin(theta), cos(theta)*cos(alpha), -cos(theta)*sin(alpha), sin(theta)*a],
    [0, sin(alpha), cos(alpha),d],
    [0,0,0,1]]
    return dh
qs = [q1,q2,q3]
ds = [0,0,0]
aas = [a1,a2,a3]
alphas = [0,0,0]
t = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
z0,z1,z2 =np.array([0,0,1]),np.array([0,0,1]),np.array([0,0,1])
o = [[],[],[]]
o0 = [0,0,0]
for i in range(0,3):
    t = np.dot(t,get_dh(qs[i],alphas[i],ds[i],aas[i]))
    o[i] = np.dot(t,[0,0,0,1])[0:3]
jacob = [np.transpose(np.cross(z0,o[2]-o0)).tolist(),np.transpose(np.cross(z1,o[2]-o[0])).tolist(),np.transpose(np.cross(z1,o[2]-o[1])).tolist()],[np.transpose(z0).tolist(),np.transpose(z1).tolist(),np.transpose(z2).tolist()]
print("Jacob :" + str(jacob))

Jacob :([[-11.156448908138957, 9.335387362109374, 0.0], [-8.657598394923445, 5.004596890082059, 0.0], [-4.328799197461723, 2.5022984450410295, 0.0]], [[0, 0, 1], [0, 0, 1], [0, 0, 1]])
