RRR manipulator

In [28]:
import numpy as np
import sympy as symp
import math
l1,l2,l3 = map(int,input("Enter the length of 1st limb, 2nd limb, and 3rd limb : ").split())

theta1=float(input('Enter the value of joint angle 1: '))*(math.pi)/180
theta2=float(input('Enter the value of joint angle 2: '))*(math.pi)/180
theta3=float(input('Enter the value of joint angle 3: '))*(math.pi)/180


q1, q2, q3 = symp.symbols('q1 q2 q3')

# position of endeffector
x_pos=l1*symp.cos(q1)+l2*symp.cos(q1+q2)+l3*symp.cos(q1+q2+q3)
y_pos=l1*symp.sin(q1)+l2*symp.sin(q1+q2)+l3*symp.sin(q1+q2+q3)
z_pos=0

dn_0 = np.array([[x_pos], [y_pos],[z_pos]])  

x_pos_diff_q1=symp.diff(x_pos,q1)
x_pos_diff_q1=x_pos_diff_q1.subs([(q1,theta1),(q2,theta2),(q3,theta3)])   # giving values to the q1,q2,q3 as theta1,theta2,d3 respectively 

y_pos_diff_q1=symp.diff(y_pos,q1)
y_pos_diff_q1=y_pos_diff_q1.subs([(q1,theta1),(q2,theta2),(q3,theta3)])

x_pos_diff_q2=symp.diff(x_pos,q2)
x_pos_diff_q2=x_pos_diff_q2.subs([(q1,theta1),(q2,theta2),(q3,theta3)])

y_pos_diff_q2=symp.diff(y_pos,q2)
y_pos_diff_q2=y_pos_diff_q2.subs([(q1,theta1),(q2,theta2),(q3,theta3)])

x_pos_diff_q3=symp.diff(x_pos,q3)
x_pos_diff_q3=x_pos_diff_q3.subs([(q1,theta1),(q2,theta2),(q3,theta3)])

y_pos_diff_q3=symp.diff(y_pos,q3)
y_pos_diff_q3=y_pos_diff_q3.subs([(q1,theta1),(q2,theta2),(q3,theta3)])

Jv = np.array([[x_pos_diff_q1,x_pos_diff_q2,x_pos_diff_q3],
             [y_pos_diff_q1,y_pos_diff_q2,y_pos_diff_q3],
             [0,0,0]])

Jw = np.array([[0,0,0],[0,0,0],[1,1,1]])
J = np.append(Jv,Jw,axis=0)
print(J)

Enter the length of 1st limb, 2nd limb, and 3rd limb : 1 2 4
Enter the value of joint angle 1: 60
Enter the value of joint angle 2: 30
Enter the value of joint angle 3: 45
[[-5.69445252853063 -4.82842712474619 -2.82842712474619]
 [-2.32842712474619 -2.82842712474619 -2.82842712474619]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]]
