In [3]:
import numpy as np
import sympy as symp
import math
l1,l2 = map(int,input("Enter the length of 1st limb, 2nd limb: ").split())

theta1=float(input('Enter the value of joint angle 1: '))*(math.pi)/180
theta2=float(input('Enter the value of joint angle 2: '))*(math.pi)/180
d3=float(input('Enter the value of 3rd joint variable : '))


q1, q2, q3 = symp.symbols('q1 q2 q3')

# potion of end effector
x_pos=l1*symp.cos(q1)+l2*symp.cos(q1+q2)
y_pos=l1*symp.sin(q1)+l2*symp.sin(q1+q2)
z_pos=-1*q3

dn_0 = np.array([[x_pos], [y_pos],[z_pos]])  # position of endeffector

x_pos_diff_q1=symp.diff(x_pos,q1)
x_pos_diff_q1=x_pos_diff_q1.subs([(q1,theta1),(q2,theta2),(q3,d3)])  # giving values to the q1,q2,q3 as theta1,theta2,d3 respectively 

y_pos_diff_q1=symp.diff(y_pos,q1)
y_pos_diff_q1=y_pos_diff_q1.subs([(q1,theta1),(q2,theta2),(q3,d3)])

z_pos_diff_q1=symp.diff(z_pos,q1)
z_pos_diff_q1=z_pos_diff_q1.subs([(q1,theta1),(q2,theta2),(q3,d3)])

x_pos_diff_q2=symp.diff(x_pos,q2)
x_pos_diff_q2=x_pos_diff_q2.subs([(q1,theta1),(q2,theta2),(q3,d3)])

y_pos_diff_q2=symp.diff(y_pos,q2)
y_pos_diff_q2=y_pos_diff_q2.subs([(q1,theta1),(q2,theta2),(q3,d3)])

z_pos_diff_q2=symp.diff(z_pos,q2)
z_pos_diff_q2=z_pos_diff_q2.subs([(q1,theta1),(q2,theta2),(q3,d3)])

x_pos_diff_q3=symp.diff(x_pos,q3)
x_pos_diff_q3=x_pos_diff_q3.subs([(q1,theta1),(q2,theta2),(q3,d3)])

y_pos_diff_q3=symp.diff(y_pos,q3)
y_pos_diff_q3=y_pos_diff_q3.subs([(q1,theta1),(q2,theta2),(q3,d3)])

z_pos_diff_q3=symp.diff(z_pos,q3)
z_pos_diff_q3=z_pos_diff_q3.subs([(q1,theta1),(q2,theta2),(q3,d3)])


Jv = np.array([[x_pos_diff_q1,x_pos_diff_q2,x_pos_diff_q3],
             [y_pos_diff_q1,y_pos_diff_q2,y_pos_diff_q3],
             [z_pos_diff_q1,z_pos_diff_q2,z_pos_diff_q3]])   # linear velocity jacobian matrix

Jw = np.array([[0,0,0],[0,0,0],[1,1,0]])     # Angular velocity jacobian matrix
J = np.append(Jv,Jw,axis=0)   # Combine Jacobian matrix
print(J)

Enter the length of 1st limb, 2nd limb: 2 3
Enter the value of joint angle 1: 45
Enter the value of joint angle 2: 60
Enter the value of joint variable 3: 3
[[-4.31199104124030 -2.89777747886721 0]
 [0.637756427065533 -0.776457135307562 0]
 [0 0 -1]
 [0 0 0]
 [0 0 0]
 [1 1 0]]
