# Task 3

In [12]:
import numpy as np
import math

n = int(input(" Enter the number of links in your robot: "))
D_H = []
joints = [] 
for i in range(n):          
    a_i = int(input(f"Enter the value of a_i for link {i+1}: "))
    alpha_i = int(input(f"Enter the value of alpha_i for link {i+1}: "))
    d_i = int(input(f"Enter the value of d_i for link {i+1}: "))
    theta_i = int(input(f"Enter the value of theta_i for link {i+1}: "))
    D_H.append([a_i,alpha_i,d_i,theta_i])
    
k = input("Enter 'yes' if you want to provide the type of each joints and enter 'no' for all revolute joints as default: ")
if k=='yes':
    for i in range(n):  
        joint = input("Enter 'p' if joint is prismatic else enter 'r' if joint is revolute: ")
        joints.append(joint)
else:
     for i in range(n):  
        joint = 'r'
        joints.append(joint)
        
DH_par = np.array(D_H)
print(f'DH Parameters provided are:\n {DH_par} \n')

A = []

################ Homogenous transformation ###############
for i in range(n):
    r1 = [np.cos(DH_par[i,3]*math.pi/180),-1*np.sin(DH_par[i,3]*math.pi/180)*np.cos(DH_par[i,1]*math.pi/180),np.sin(DH_par[i,3]*math.pi/180)*np.sin(DH_par[i,1]*math.pi/180),DH_par[i,0]*np.cos(DH_par[i,3]*math.pi/180)]
    r2 = [np.sin(DH_par[i,3]*math.pi/180),np.cos(DH_par[i,3]*math.pi/180)*np.cos(DH_par[i,1]*math.pi/180),-1*np.cos(DH_par[i,3]*math.pi/180)*np.sin(DH_par[i,1]*math.pi/180),DH_par[i,0]*np.sin(DH_par[i,3]*math.pi/180)]
    r3 = [0,np.sin(DH_par[i,1]*math.pi/180),np.cos(DH_par[i,1]*math.pi/180),DH_par[i,2]]
    r4 = [0,0,0,1]
    A_i =np.array([r1,r2,r3,r4])
    A.append(A_i)
    
################ transformation for end- effector #############
T = []   # T is the list containing the value of A1,A1A2,A1A2A3,............., A1A2....An
Ti = np.identity(4)
for i in range(n):
    Ti = Ti@A[i]
    T.append(Ti)    
print(f'T{n}_0 is given by \n {T[n-1]} \n')

################ end- effector position #############
end_effector_pos = [T[n-1][0,3],T[n-1][1,3],T[n-1][2,3]]
print(f'\n end-effector position is \n {end_effector_pos} \n' )

O_n = np.array(end_effector_pos) # distance of end-effector from O_0
O_0 = np.array([0,0,0])
O = []                 # list contains the position of all origins
O.append(O_0)
j_v = []
j_w = []

for i in range(n):
    O_i = np.array([T[i][0,3],T[i][1,3],T[i][2,3]])
    O.append(O_i)
    
    Z_i = np.array([T[i][0,2],T[i][1,2],T[i][2,2]])   # Z_i is R_i_0 * k_i_0
    
    rv = np.cross(Z_i,(O_n - O[i]))             # rv denotes revolute joint value of element of velocity Jacobian
    pv = Z_i                                    # pv denotes prismatic joint value of element of velocity Jacobian
    if joints[i]=='p':
        j_v.append(pv)
        j_w.append(O_0)
    else:
        j_v.append(rv)
        j_w.append(pv)
        
Jv = np.transpose(np.array(j_v))    # velocity Jacobian
Jw = np.transpose(np.array(j_w))    # Angular velocity Jacobian
J = np.append(Jv,Jw,axis=0)         # Manipulator Jacobian
print(f"Manipulator Jacobian is \n {J}")



        
        
    
        
    
    

 Enter the number of links in your robot: 2
Enter the value of a_i for link 1: 1
Enter the value of alpha_i for link 1: 0
Enter the value of d_i for link 1: 0
Enter the value of theta_i for link 1: 90
Enter the value of a_i for link 2: 1
Enter the value of alpha_i for link 2: 0
Enter the value of d_i for link 2: 0
Enter the value of theta_i for link 2: 0
Enter 'yes' if you want to provide the type of each joints and enter 'no' for all revolute joints as default: no
DH Parameters provided are:
 [[ 1  0  0 90]
 [ 1  0  0  0]] 

T2_0 is given by 
 [[ 6.1232340e-17 -1.0000000e+00  0.0000000e+00  1.2246468e-16]
 [ 1.0000000e+00  6.1232340e-17  0.0000000e+00  2.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]] 


 end-effector position is 
 [1.2246467991473532e-16, 2.0, 0.0] 

Manipulator Jacobian is 
 [[-2.0000000e+00 -1.0000000e+00]
 [ 1.2246468e-16  6.1232340e-17]
 [ 0.0000000e+00  0.0000000e+00]
 [ 

# Task 4


In [13]:


# For Stanford type stanford.xlsx
# For Scara type scara.xlsx

import numpy as np
import pandas as pd
import math

user = input("Enter the excel file name 'scara.xlsx' for scara or 'stanford.xlsx' for stanford: ")
data = pd.read_excel(user)
DH_par = data.to_numpy() # converting the dataframe into numpy array
n = DH_par.shape[0]
print(f"DH Parameter table is: \n{DH_par}\n")
A = []

################ Homogenous transformation ###############
for i in range(n):
    r1 = [np.cos(DH_par[i,3]*math.pi/180),-1*np.sin(DH_par[i,3]*math.pi/180)*np.cos(DH_par[i,1]*math.pi/180),np.sin(DH_par[i,3]*math.pi/180)*np.sin(DH_par[i,1]*math.pi/180),DH_par[i,0]*np.cos(DH_par[i,3]*math.pi/180)]
    r2 = [np.sin(DH_par[i,3]*math.pi/180),np.cos(DH_par[i,3]*math.pi/180)*np.cos(DH_par[i,1]*math.pi/180),-1*np.cos(DH_par[i,3]*math.pi/180)*np.sin(DH_par[i,1]*math.pi/180),DH_par[i,0]*np.sin(DH_par[i,3]*math.pi/180)]
    r3 = [0,np.sin(DH_par[i,1]*math.pi/180),np.cos(DH_par[i,1]*math.pi/180),DH_par[i,2]]
    r4 = [0,0,0,1]
    A_i =np.array([r1,r2,r3,r4])
    A.append(A_i)
    
################ transformation for end- effector #############
T = []         # T is the list containing the value of A1,A1A2,A1A2A3,............., A1A2....An
Ti = np.identity(4)
for i in range(n):
    Ti = Ti@A[i]
    T.append(Ti)    
print(f'T{n}_0 is given by \n {T[n-1]} \n')



Enter the excel file name 'scara.xlsx' for scara or 'stanford.xlsx' for stanford: scara.xlsx
DH Parameter table is: 
[[  3   0   0  30]
 [  4 180   0  45]
 [  0   0   2   0]
 [  0   0   3  60]]

T4_0 is given by 
 [[ 9.65925826e-01  2.58819045e-01  1.18291797e-16  3.63335239e+00]
 [ 2.58819045e-01 -9.65925826e-01 -3.16961915e-17  5.36370331e+00]
 [ 1.06057524e-16  6.12323400e-17 -1.00000000e+00 -5.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]] 



# Task5

In [14]:
import numpy as np
import math
import pandas as pd

user = 'task5.xlsx'
data = pd.read_excel(user)
DH_par = data.to_numpy() # converting the dataframe into numpy array
n = DH_par.shape[0]
print(f"DH Parameter table is: \n{DH_par}\n")
A = []
################ Homogenous transformation ###############
for i in range(n):
    r1 = [np.cos(DH_par[i,3]*math.pi/180),-1*np.sin(DH_par[i,3]*math.pi/180)*np.cos(DH_par[i,1]*math.pi/180),np.sin(DH_par[i,3]*math.pi/180)*np.sin(DH_par[i,1]*math.pi/180),DH_par[i,0]*np.cos(DH_par[i,3]*math.pi/180)]
    r2 = [np.sin(DH_par[i,3]*math.pi/180),np.cos(DH_par[i,3]*math.pi/180)*np.cos(DH_par[i,1]*math.pi/180),-1*np.cos(DH_par[i,3]*math.pi/180)*np.sin(DH_par[i,1]*math.pi/180),DH_par[i,0]*np.sin(DH_par[i,3]*math.pi/180)]
    r3 = [0,np.sin(DH_par[i,1]*math.pi/180),np.cos(DH_par[i,1]*math.pi/180),DH_par[i,2]]
    r4 = [0,0,0,1]
    A_i =np.array([r1,r2,r3,r4])
    A.append(A_i)
    
################ transformation for end- effector #############
T = []   # T is the list containing the value of A1,A1A2,A1A2A3,............., A1A2....An
Ti = np.identity(4)
for i in range(n):
    Ti = Ti@A[i]
    T.append(Ti)    
print(f'T{n}_0 is given by \n {T[n-1]} \n')


DH Parameter table is: 
[[  0 -90   2   0]
 [  0 -90   3 -90]
 [  0   0   4   0]]

T3_0 is given by 
 [[ 6.123234e-17  6.123234e-17  1.000000e+00  4.000000e+00]
 [-6.123234e-17 -1.000000e+00  6.123234e-17  3.000000e+00]
 [ 1.000000e+00 -6.123234e-17 -6.123234e-17  2.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]] 



# Task6


In [15]:
import numpy as np
import math
import pandas as pd

user = 'task6.xlsx'
data = pd.read_excel(user)
DH_par = data.to_numpy() # converting the dataframe into numpy array
n = DH_par.shape[0]
print(f"DH Parameter table is: \n{DH_par}\n")
A = []
################ Homogenous transformation ###############
for i in range(n):
    r1 = [np.cos(DH_par[i,3]*math.pi/180),-1*np.sin(DH_par[i,3]*math.pi/180)*np.cos(DH_par[i,1]*math.pi/180),np.sin(DH_par[i,3]*math.pi/180)*np.sin(DH_par[i,1]*math.pi/180),DH_par[i,0]*np.cos(DH_par[i,3]*math.pi/180)]
    r2 = [np.sin(DH_par[i,3]*math.pi/180),np.cos(DH_par[i,3]*math.pi/180)*np.cos(DH_par[i,1]*math.pi/180),-1*np.cos(DH_par[i,3]*math.pi/180)*np.sin(DH_par[i,1]*math.pi/180),DH_par[i,0]*np.sin(DH_par[i,3]*math.pi/180)]
    r3 = [0,np.sin(DH_par[i,1]*math.pi/180),np.cos(DH_par[i,1]*math.pi/180),DH_par[i,2]]
    r4 = [0,0,0,1]
    A_i =np.array([r1,r2,r3,r4])
    A.append(A_i)
    
################ transformation for end- effector #############
T = []   # T is the list containing the value of A1,A1A2,A1A2A3,............., A1A2....An
Ti = np.identity(4)
for i in range(n):
    Ti = Ti@A[i]
    T.append(Ti)    
print(f'T{n}_0 is given by \n {T[n-1]} \n')


DH Parameter table is: 
[[  0  90   2  30]
 [  2   0   0  60]
 [  2   0   0  45]
 [  0 -90   0  30]
 [  0 -90   0  60]
 [  0   0   4  90]]

T6_0 is given by 
 [[ 0.61237244  0.73919892  0.28033009  1.53905801]
 [ 0.35355339 -0.5732233   0.73919892  3.19797663]
 [ 0.70710678 -0.35355339 -0.61237244  3.21441272]
 [ 0.          0.          0.          1.        ]] 

